import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
} from 'class-validator';
import { IsBooleanValue } from '@/common/decorators/is-boolean-value.decorator';

/** `sort_order` is a signed SMALLINT. */
export const MAX_SORT_ORDER = 32767;

/**
 * NOTE: `code` is intentionally NOT part of this DTO.
 *
 * `departments.code` is generated by the server (`PB0001`, `PB0002`…). Asking a
 * user to invent a unique identifier before they can save is a poor deal, and
 * hand-typed codes drift in practice (`IT`, `it`, `CNTT`, `IT_DEPT` all meaning
 * one department). The global ValidationPipe runs with `whitelist: true`, so a
 * client that still sends `code` has it stripped rather than honoured.
 */
export class CreateDepartmentDto {
  @ApiProperty({ example: 'Phòng Tài chính', maxLength: 150 })
  @IsString()
  @IsNotEmpty()
  @MaxLength(150)
  name: string;

  @ApiPropertyOptional({ example: 'Quản lý thu chi, kế toán', nullable: true })
  @IsOptional()
  @IsString()
  description?: string | null;

  @ApiPropertyOptional({
    example: null,
    nullable: true,
    description: 'Phòng ban cha; null = phòng ban gốc',
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  parentId?: number | null;

  @ApiPropertyOptional({
    example: null,
    nullable: true,
    description: 'employees.id của trưởng phòng',
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  managerId?: number | null;

  @ApiPropertyOptional({ example: 0, minimum: 0, maximum: MAX_SORT_ORDER })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(MAX_SORT_ORDER)
  sortOrder?: number;

  @ApiPropertyOptional({ example: true, default: true })
  @IsOptional()
  @IsBooleanValue()
  isActive?: boolean;
}
