import { useTranslation } from 'react-i18next';
import styles from './GeneratedCodeField.module.css';

/**
 * The record's code, shown as context inside an edit modal.
 *
 * `code` is generated by the server (`PB0001`, `CV0001`, `NP0001`) and is
 * immutable: it is on every response but on none of the create/update payloads.
 * The user still needs to see WHICH record they are editing, so it is rendered
 * here as plain text.
 *
 * Deliberately NOT a `<Form.Item>` with a disabled `<Input>`: a greyed-out input
 * still looks like a field that could become editable, and it would register a
 * form value for something the API would strip. There is no control, so there is
 * no `<label>` either — just a caption, the value, and one line saying why it
 * cannot be changed.
 *
 * Rendered only when editing; a create form has no code yet.
 */
export interface GeneratedCodeFieldProps {
  code: string;
}

export function GeneratedCodeField({ code }: GeneratedCodeFieldProps) {
  const { t } = useTranslation();

  return (
    <div className={styles.field}>
      <span className={styles.caption}>{t('settings.fields.codeLabel')}</span>
      <span className={styles.value}>{code}</span>
      <span className={styles.hint}>{t('settings.fields.codeGenerated')}</span>
    </div>
  );
}
